spring:
  profiles:
    active : local
---
spring:
  profiles : local
  datasource:
    data: classpath: data-h2.sql
  jpa

---
spring:
  profiles: set1
server:
  port: 8081
---
spring:
  profiles: set2
server:
  port: 8082
